name: Implement Algorithm
description: Implement a new algorithm.
title: <the name will be auto fill>   # This is a placeholder; will be replaced by GitHub Actionslabels: [enhancement]

body:
- type: input
  id: algo_name  # ✅ This must match exactly
  attributes:
    label: Algo_Name
    description: Replace spaces with underscores and use lowercase.
    placeholder: 'Example: bubble_sort'
  validations:
    required: true

- type: textarea
  attributes:
    label: Other
    placeholder: If the issue needs any other detail add it in this section.