name: Implement Algorithm
description: Implement a new algorithm.
title: <leave empty>  # Will be replaced by GitHub Actions
labels: [enhancement]

body:
- type: input
  id: algo_name    # This can be anything, but `label` must match Action
  attributes:
    label: Algo_Name    # This must exactly match what's used in your action script
    description: Replace spaces with underscores and use lowercase.
    placeholder: 'Example: bubble_sort'
  validations:
    required: true
