name: Implement Algorithm
description: Implement a new algorithm.
title: <Leave this empty>
labels: [enhancement]

body:
- type: input
  id: Algo_name
  attributes:
    label: Algo_Name
    description: Replace spaces with underscores and use lowercase.
    placeholder: 'Example: bubble_sort'
  validations:
    required: true
