name: Bug Report
description: File a bug report.
title: '🐛 [Bug]: '
labels: [bug]

body:
- type: dropdown
  attributes:
    label: Severity
    options:
    - 🔥 Blocker
    - 🛑 Major
    - ⚠️ Minor
    - ❓ Not sure
    default: 0

- type: textarea
  attributes:
    label: To Reproduce
    placeholder: Enumerate all the steps to reproduce the bug.

- type: textarea
  attributes:
    label: Expected behavior
    placeholder: A clear and concise description of what you expected to happen.

- type: textarea
  attributes:
    label: Other
    placeholder: If the report needs any other detail add it in this section.
