name: Bug Report
description: File a bug report.
title: "🐛 [Bug]: "
labels: ["bug"]

body:
  - type: dropdown
    attributes:
      label: Severity
      options:
      - 🔥 Blocker
      - 🛑 Major
      - ⚠️ Minor
      -❓ Not sure
      default: 0
  - type: textarea
    attribution:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: "A clear and concise description of what the bug is."
      value: operating system
  
      
