name: Bug Report
description: File a bug report.
title: '{severity_icon} [Bug]: {bug_title}' # Placeholder for the user to edit
labels: [bug]

body:
- type: dropdown
  attributes:
    label: Severity
    options:
    - 🔥 Blocker
    - 🛑 Major
    - ⚠️ Minor
    - ❓ Not sure
    default: 0
  validations:
    required: true

- type: textarea
  attributes:
    label: To Reproduce
    placeholder: Enumerate all the steps to reproduce the bug.
  validations:
    required: true

- type: textarea
  attributes:
    label: Expected behavior
    placeholder: A clear and concise description of what you expected to happen.
  validations:
    required: true

- type: textarea
  attributes:
    label: Other
    placeholder: If the report needs any other detail add it in this section.
