name: Bug Report
description: File a bug report.
title: 'Enter a short title that describes the issue' # Placeholder for the user to edit
labels: [bug]

body:
- type: dropdown
  attributes:
    label: Severity
    options:
    - 🔥 Blocker
    - 🛑 Major
    - ⚠️ Minor
    - ❓ Not sure
    default: 0
  validations:
    required: true

- type: textarea
  attributes:
    label: Steps to Reproduce & What Happens
    placeholder: Enumerate all the steps to reproduce the bug.
  validations:
    required: true

- type: textarea
  attributes:
    label: Expected behavior
    placeholder: A clear and concise description of what you expected to happen.
  validations:
    required: true
