name: Bug Report
description: File a bug report.
title: 'Enter a short title that describes the issue'
labels: [bug]

body:
- type: dropdown
  attributes:
    label: Type
    options:
    - 🧮 Algorithm Implementation 
    - 🛠 CI/Tooling Issue 
    - 📘 Algorithm Documentation 
    - 🖋 General Documentation
    - 🧪 Test Failure or Adding Testcase 
    - ❓ Other / Not Sure 

    default: 0
  validations:
    required: true

- type: textarea
  attributes:
    label: Steps to Reproduce & What Happens
    placeholder: Enumerate all the steps to reproduce the bug.
  validations:
    required: true

- type: textarea
  attributes:
    label: Expected behavior
    placeholder: A clear and concise description of what you expected to happen.
  validations:
    required: true
