name: Auto-fill Algorithm Title

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  update-issue-title:
    runs-on: ubuntu-latest
    steps:
      - name: Debug and Update Title(algo)
        uses: actions/github-script@v7
        with:
          script: |
            const issueBody = context.payload.issue.body;
            console.log("Issue Body:");
            console.log(issueBody);

            const match = /"algo_name":"(.*?)"/.exec(JSON.stringify(issueBody));
            if (!match) {
              console.log("🚫 No algo_name match found in issue body.");
              return;
            }

            const algoName = match[1];
            const issueNumber = context.issue.number;
            const newTitle = `✨ Implement ${algoName}`;
            console.log(`✅ Found algo_name: ${algoName}`);
            console.log(`🔧 Updating issue #${issueNumber} title to: ${newTitle}`);

            await github.rest.issues.update({
              ...context.repo,
              issue_number: issueNumber,
              title: newTitle
            });
