name: Auto-fill Algorithm Title

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  update-issue-title:
    runs-on: ubuntu-latest
    steps:
      - name: Parse markdown and update title
        uses: actions/github-script@v7
        with:
          script: |
            const issueBody = context.payload.issue.body;
            console.log("Issue Body:\n", issueBody);

            // Match the content under the "### Algo_Name" section
            const match = /### Algo_Name\s+(.+?)\s+(###|$)/s.exec(issueBody);
            if (!match) {
              console.log("🚫 Could not find algo name in Markdown.");
              return;
            }

            const algoName = match[1].trim();
            const issueNumber = context.issue.number;
            const newTitle = `✨ Implement ${algoName}`;

            console.log(`✅ Extracted algo name: ${algoName}`);
            console.log(`🔧 Updating issue title to: ${newTitle}`);

            await github.rest.issues.update({
              ...context.repo,
              issue_number: issueNumber,
              title: newTitle
            });
