name: Auto-fill Algorithm Title

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  update-issue-title:
    runs-on: ubuntu-latest
    steps:
    - name: Parse template and update title
      uses: actions/github-script@v7
      with:
        script: |
          const issueBody = context.payload.issue.body;
          console.log("Issue Body:\n", issueBody);

          const getField = (label) => {
            const match = new RegExp(`${label}":\\s*"([^"]+)`).exec(JSON.stringify(issueBody));
            return match ? match[1] : null;
          };

          const algoName = getField("Algo_Name");
          if (!algoName) {
            console.log("🚫 Could not find algo name.");
            return;
          }

          const newTitle = `✨ Implement ${algoName}`;
          const issueNumber = context.issue.number;

          console.log(`✅ Extracted algo name: ${algoName}`);
          console.log(`🔧 Updating issue title to: ${newTitle}`);

          await github.rest.issues.update({
            ...context.repo,
            issue_number: issueNumber,
            title: newTitle
          });
