name: Auto-fill Bug Title

on:
  issues:
    types: [opened]

jobs:
  update-issue-title:
    runs-on: ubuntu-latest
    steps:
    - name: Format Title from Severity and Bug Title
      uses: actions/github-script@v7
      with:
        script: |
          const body = context.payload.issue.body;

          const getField = (label) => {
            const match = new RegExp(`${label}":"([^"]+)`).exec(JSON.stringify(body));
            return match ? match[1] : null;
          };

          const severityMap = {
            "🔥 Blocker": "🔥",
            "🛑 Major": "🛑",
            "⚠️ Minor": "⚠️",
            "❓ Not sure": "❓"
          };

          let severity = getField('severity');
          const severityIcon = severityMap[severity] || "❓"; // fallback to ❓

          const bugTitle = getField('bug_title');
          if (!severity || !bugTitle) return;

          const issueNumber = context.issue.number;

          // Update the issue title
          await github.rest.issues.update({
            ...context.repo,
            issue_number: issueNumber,
            title: `${severityIcon} [Bug]: ${bugTitle}`
          });
