name: Code Tester

on: 
  pull_request:
    branch: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Download Repo In Docker
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      id: test
      run: pytest
