name: Code Tester

on: [pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - name: Download Repo In Docker
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install rich
        pip install ruff
        pip install pytest

    - name: Run tests
      run: pytest tests --collect-only

    - name: Style Check
      run: ruff check
