name: Issue Automatic Renaming

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  rename-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Rename for New Algo Issues
        uses: actions/github-script@v7
        if: contains(github.event.issue.body, '### Algo_Name')
        with:
          script: |
            const issueBody = context.payload.issue.body;
            console.log("Issue Body:\n", issueBody);

            const match = /### Algo_Name\s*\n+(.+?)(\n+###|\n*$)/s.exec(issueBody);
            if (!match) {
              console.log("🚫 Could not find algo name in Markdown.");
              return;
            }

            const algoName = match[1].trim();
            const issueNumber = context.issue.number;
            const newTitle = `✨ Implement ${algoName}`;

            console.log(`🔧 Updating issue title to: ${newTitle}`);

            await github.rest.issues.update({
              ...context.repo,
              issue_number: issueNumber,
              title: newTitle
            });

      - name: Rename for Bug Report Issues
        uses: actions/github-script@v7
        if: contains(github.event.issue.body, '### Severity')
        with:
          script: |
            const body = context.payload.issue.body;
            console.log("Issue Body:\n", body);

            const severityMatch = /### Severity\s+(.+?)\s*(###|$)/s.exec(body);
            const severity = severityMatch ? severityMatch[1].trim() : null;

            if (!severity) {
              console.log("🚫 Could not find severity in Markdown.");
              return;
            }

            const severityMap = {
              "🧮 Algorithm Implementation": "🧮",
              "🛠 CI/Tooling Issue": "🛠",
              "📘 Algorithm Documentation": "📘",
              "🖋 General Documentation": "🖋",
              "🧪 Test Failure or Adding Testcase": "🧪",
              "❓ Other / Not Sure": "❓",
            };
            const severityIcon = severityMap[severity] || "❓";

            const rawTitle = context.payload.issue.title;
            if (rawTitle.startsWith("🔥") || rawTitle.startsWith("🛑") || rawTitle.startsWith("⚠️") || rawTitle.startsWith("❓")) {
              console.log("✅ Title already formatted correctly.");
              return;
            }

            const issueNumber = context.issue.number;
            const updatedTitle = `⚠️ - ${severityIcon} [Bug]: ${rawTitle}`;

            console.log(`🔧 Updating issue title to: ${updatedTitle}`);

            await github.rest.issues.update({
              ...context.repo,
              issue_number: issueNumber,
              title: updatedTitle
            });
