name: Issue Automatic Renaming

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  steps:
    runs-on: ubuntu-latest
    rename-new-algo-issue:
    - name: Parse markdown and update title
      uses: actions/github-script@v7
      with:
        script: |
          const issueBody = context.payload.issue.body;
          console.log("Issue Body:\n", issueBody);

          // Match the content under the "### Algo_Name" section
          const match = /### Algo_Name\s*\n+(.+?)(\n+###|\n*$)/s.exec(issueBody);
          if (!match) {
            console.log("🚫 Could not find algo name in Markdown.");
            return;
          }

          const algoName = match[1].trim();
          const issueNumber = context.issue.number;
          const newTitle = `✨ Implement ${algoName}`;

          console.log(`🔧 Updating issue title to: ${newTitle}`);

          await github.rest.issues.update({
            ...context.repo,
            issue_number: issueNumber,
            title: newTitle
          });
 
jobs:
  step:
    runs-on: ubuntu-latest
    rename-bug-report-issues:
      - name: Extract severity and bug title from Markdown
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.issue.body;
            console.log("Issue Body:\n", body);

            const severityMatch = /### Severity\s+(.+?)\s+(###|$)/s.exec(body);
            const severity = severityMatch ? severityMatch[1].trim() : null;

            const rawTitle = context.payload.issue.title;

            if (!severityMatch) {
              console.log("🚫 Could not find severity in Markdown.");
              return;
            }

            const severityMap = {
              "🔥 Blocker": "🔥",
              "🛑 Major": "🛑",
              "⚠️ Minor": "⚠️",
              "❓ Not sure": "❓"
            };
            const severityIcon = severityMap[severity] || "❓";

            if (rawTitle.startsWith("🔥") || rawTitle.startsWith("🛑") || rawTitle.startsWith("⚠️") || rawTitle.startsWith("❓")) {
              console.log("✅ Title already formatted correctly.");
              return;
            }

            const issueNumber = context.issue.number;
            const updatedTitle = `${severityIcon} [Bug]: ${rawTitle}`;
            console.log(`🔧 Updating issue title to: ${newTitle}`);

            await github.rest.issues.update({
              ...context.repo,
              issue_number: issueNumber,
              title: updatedTitle
            });
